<?XML VERSION="1.0"?>


<!--
	Bayesian network in BIF (BayesNet Interchange Format)
	Produced by JavaBayes (http://www.cs.cmu.edu/~javabayes/
	Output created Thu Aug 06 08:17:31 GMT+01:00 1998
-->



<!-- DTD for the BIF format -->
<!DOCTYPE BIF [
	<!ELEMENT BIF ( NETWORK )*>
	<!ELEMENT PROPERTY (#PCDATA)>
	<!ELEMENT TYPE (#PCDATA)>
	<!ELEMENT VALUE (#PCDATA)>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT NETWORK
	    ( NAME, ( PROPERTY | VARIABLE | PROBABILITY )* )>
	<!ELEMENT VARIABLE ( NAME, TYPE, ( VALUE |  PROPERTY )* ) >
	<!ELEMENT PROBABILITY
	    ( FOR | GIVEN | TABLE | ENTRY | DEFAULT | PROPERTY )* >
	<!ELEMENT FOR (#PCDATA)>
	<!ELEMENT GIVEN (#PCDATA)>
	<!ELEMENT TABLE (#PCDATA)>
	<!ELEMENT DEFAULT (TABLE)>
	<!ELEMENT ENTRY ( VALUE* , TABLE )>
]>


<BIF>
<NETWORK>
<NAME>Hailfinder</NAME>

<!-- Variables -->
<VARIABLE>
	<NAME>WindFieldMt</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Westerly</VALUE>
	<VALUE>LVorOther</VALUE>
	<PROPERTY>position = (832, 590)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>MorningCIN</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>None</VALUE>
	<VALUE>PartInhibit</VALUE>
	<VALUE>Stifling</VALUE>
	<VALUE>TotalInhibit</VALUE>
	<PROPERTY>position = (418, 311)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>VISCloudCov</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Cloudy</VALUE>
	<VALUE>PC</VALUE>
	<VALUE>Clear</VALUE>
	<PROPERTY>position = (676, 44)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>IRCloudCover</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Cloudy</VALUE>
	<VALUE>PC</VALUE>
	<VALUE>Clear</VALUE>
	<PROPERTY>position = (560, 42)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>AMInstabMt</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>None</VALUE>
	<VALUE>Weak</VALUE>
	<VALUE>Strong</VALUE>
	<PROPERTY>position = (245, 36)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>R5Fcst</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>NIL</VALUE>
	<VALUE>SIG</VALUE>
	<VALUE>SVR</VALUE>
	<PROPERTY>position = (468, 632)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>MountainFcst</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>NIL</VALUE>
	<VALUE>SIG</VALUE>
	<VALUE>SVR</VALUE>
	<PROPERTY>position = (396, 609)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>MeanRH</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>VeryMoist</VALUE>
	<VALUE>Average</VALUE>
	<VALUE>Dry</VALUE>
	<PROPERTY>position = (783, 528)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>MidLLapse</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>CloseToDryAd</VALUE>
	<VALUE>Steep</VALUE>
	<VALUE>ModerateOrLe</VALUE>
	<PROPERTY>position = (1061, 155)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>RHRatio</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>MoistMDryL</VALUE>
	<VALUE>DryMMoistL</VALUE>
	<VALUE>Other</VALUE>
	<PROPERTY>position = (996, 415)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>LoLevMoistAd</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>StrongPos</VALUE>
	<VALUE>WeakPos</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Negative</VALUE>
	<PROPERTY>position = (577, 285)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>LowLLapse</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>CloseToDryAd</VALUE>
	<VALUE>Steep</VALUE>
	<VALUE>ModerateOrLe</VALUE>
	<VALUE>Stable</VALUE>
	<PROPERTY>position = (857, 440)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>MvmtFeatures</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>StrongFront</VALUE>
	<VALUE>MarkedUpper</VALUE>
	<VALUE>OtherRapid</VALUE>
	<VALUE>NoMajor</VALUE>
	<PROPERTY>position = (1028, 542)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>TempDis</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>QStationary</VALUE>
	<VALUE>Moving</VALUE>
	<VALUE>None</VALUE>
	<VALUE>Other</VALUE>
	<PROPERTY>position = (1069, 456)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>WindAloft</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>LV</VALUE>
	<VALUE>SWQuad</VALUE>
	<VALUE>NWQuad</VALUE>
	<VALUE>AllElse</VALUE>
	<PROPERTY>position = (774, 228)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>AMCINInScen</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>LessThanAve</VALUE>
	<VALUE>Average</VALUE>
	<VALUE>MoreThanAve</VALUE>
	<PROPERTY>position = (361, 355)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>CapChange</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Decreasing</VALUE>
	<VALUE>LittleChange</VALUE>
	<VALUE>Increasing</VALUE>
	<PROPERTY>position = (270, 463)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>SynForcng</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>SigNegative</VALUE>
	<VALUE>NegToPos</VALUE>
	<VALUE>SigPositive</VALUE>
	<VALUE>PosToNeg</VALUE>
	<VALUE>LittleChange</VALUE>
	<PROPERTY>position = (913, 493)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>SatContMoist</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>VeryWet</VALUE>
	<VALUE>Wet</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Dry</VALUE>
	<PROPERTY>position = (351, 37)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>RaoContMoist</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>VeryWet</VALUE>
	<VALUE>Wet</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Dry</VALUE>
	<PROPERTY>position = (424, 57)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>CombMoisture</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>VeryWet</VALUE>
	<VALUE>Wet</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Dry</VALUE>
	<PROPERTY>position = (383, 107)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>LatestCIN</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>None</VALUE>
	<VALUE>PartInhibit</VALUE>
	<VALUE>Stifling</VALUE>
	<VALUE>TotalInhibit</VALUE>
	<PROPERTY>position = (425, 404)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>LLIW</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Unfavorable</VALUE>
	<VALUE>Weak</VALUE>
	<VALUE>Moderate</VALUE>
	<VALUE>Strong</VALUE>
	<PROPERTY>position = (374, 407)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Date</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>May15_Jun14</VALUE>
	<VALUE>Jun15_Jul1</VALUE>
	<VALUE>Jul2_Jul15</VALUE>
	<VALUE>Jul16_Aug10</VALUE>
	<VALUE>Aug11_Aug20</VALUE>
	<VALUE>Aug20_Sep15</VALUE>
	<PROPERTY>position = (1024, 29)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>WindFieldPln</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>LV</VALUE>
	<VALUE>DenvCyclone</VALUE>
	<VALUE>LongAnticyc</VALUE>
	<VALUE>E_NE</VALUE>
	<VALUE>SEQuad</VALUE>
	<VALUE>WidespdDnsl</VALUE>
	<PROPERTY>position = (746, 476)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Dewpoints</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>LowEvrywhere</VALUE>
	<VALUE>LowAtStation</VALUE>
	<VALUE>LowSHighN</VALUE>
	<VALUE>LowNHighS</VALUE>
	<VALUE>LowMtsHighPl</VALUE>
	<VALUE>HighEvrywher</VALUE>
	<VALUE>Other</VALUE>
	<PROPERTY>position = (1073, 291)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>SfcWndShfDis</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>DenvCyclone</VALUE>
	<VALUE>E_W_N</VALUE>
	<VALUE>E_W_S</VALUE>
	<VALUE>MovingFtorOt</VALUE>
	<VALUE>DryLine</VALUE>
	<VALUE>None</VALUE>
	<VALUE>Other</VALUE>
	<PROPERTY>position = (930, 603)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>InsChange</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Decreasing</VALUE>
	<VALUE>LittleChange</VALUE>
	<VALUE>Increasing</VALUE>
	<PROPERTY>position = (504, 419)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>MorningBound</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>None</VALUE>
	<VALUE>Weak</VALUE>
	<VALUE>Strong</VALUE>
	<PROPERTY>position = (16, 257)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>OutflowFrMt</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>None</VALUE>
	<VALUE>Weak</VALUE>
	<VALUE>Strong</VALUE>
	<PROPERTY>position = (198, 310)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>WndHodograph</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>DCVZFavor</VALUE>
	<VALUE>StrongWest</VALUE>
	<VALUE>Westerly</VALUE>
	<VALUE>Other</VALUE>
	<PROPERTY>position = (197, 81)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>N34StarFcst</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>NIL</VALUE>
	<VALUE>SIG</VALUE>
	<VALUE>SVR</VALUE>
	<PROPERTY>position = (544, 609)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>AreaMoDryAir</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>VeryWet</VALUE>
	<VALUE>Wet</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Dry</VALUE>
	<PROPERTY>position = (386, 167)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>CombClouds</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Cloudy</VALUE>
	<VALUE>PC</VALUE>
	<VALUE>Clear</VALUE>
	<PROPERTY>position = (605, 111)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>ScenRelAMCIN</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>AB</VALUE>
	<VALUE>CThruK</VALUE>
	<PROPERTY>position = (348, 287)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>LIfr12ZDENSd</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>LIGt0</VALUE>
	<VALUE>N1GtLIGt_4</VALUE>
	<VALUE>N5GtLIGt_8</VALUE>
	<VALUE>LILt_8</VALUE>
	<PROPERTY>position = (622, 324)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>AMDewptCalPl</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Instability</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Stability</VALUE>
	<PROPERTY>position = (681, 367)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>AMInsWliScen</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>LessUnstable</VALUE>
	<VALUE>Average</VALUE>
	<VALUE>MoreUnstable</VALUE>
	<PROPERTY>position = (566, 416)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>N0_7muVerMo</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>StrongUp</VALUE>
	<VALUE>WeakUp</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Down</VALUE>
	<PROPERTY>position = (84, 29)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>SubjVertMo</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>StronUp</VALUE>
	<VALUE>WeakUp</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Down</VALUE>
	<PROPERTY>position = (26, 101)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>QGVertMotion</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>StrongUp</VALUE>
	<VALUE>WeakUp</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Down</VALUE>
	<PROPERTY>position = (128, 57)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>CombVerMo</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>StrongUp</VALUE>
	<VALUE>WeakUp</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Down</VALUE>
	<PROPERTY>position = (42, 168)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>AreaMeso_ALS</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>StrongUp</VALUE>
	<VALUE>WeakUp</VALUE>
	<VALUE>Neutral</VALUE>
	<VALUE>Down</VALUE>
	<PROPERTY>position = (95, 197)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>CldShadeOth</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Cloudy</VALUE>
	<VALUE>PC</VALUE>
	<VALUE>Clear</VALUE>
	<PROPERTY>position = (279, 252)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Boundaries</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>None</VALUE>
	<VALUE>Weak</VALUE>
	<VALUE>Strong</VALUE>
	<PROPERTY>position = (55, 372)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>CldShadeConv</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>None</VALUE>
	<VALUE>Some</VALUE>
	<VALUE>Marked</VALUE>
	<PROPERTY>position = (141, 270)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>InsInMt</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>None</VALUE>
	<VALUE>Weak</VALUE>
	<VALUE>Strong</VALUE>
	<PROPERTY>position = (290, 123)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>ScenRel3_4</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>ACEFK</VALUE>
	<VALUE>B</VALUE>
	<VALUE>D</VALUE>
	<VALUE>GJ</VALUE>
	<VALUE>HI</VALUE>
	<PROPERTY>position = (620, 592)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>ScenRelAMIns</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>ABI</VALUE>
	<VALUE>CDEJ</VALUE>
	<VALUE>F</VALUE>
	<VALUE>G</VALUE>
	<VALUE>H</VALUE>
	<VALUE>K</VALUE>
	<PROPERTY>position = (754, 286)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>CompPlFcst</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>IncCapDecIns</VALUE>
	<VALUE>LittleChange</VALUE>
	<VALUE>DecCapIncIns</VALUE>
	<PROPERTY>position = (173, 435)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>CurPropConv</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>None</VALUE>
	<VALUE>Slight</VALUE>
	<VALUE>Moderate</VALUE>
	<VALUE>Strong</VALUE>
	<PROPERTY>position = (421, 463)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Scenario</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>A</VALUE>
	<VALUE>B</VALUE>
	<VALUE>C</VALUE>
	<VALUE>D</VALUE>
	<VALUE>E</VALUE>
	<VALUE>F</VALUE>
	<VALUE>G</VALUE>
	<VALUE>H</VALUE>
	<VALUE>I</VALUE>
	<VALUE>J</VALUE>
	<VALUE>K</VALUE>
	<PROPERTY>position = (1029, 100)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>CapInScen</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>LessThanAve</VALUE>
	<VALUE>Average</VALUE>
	<VALUE>MoreThanAve</VALUE>
	<PROPERTY>position = (324, 467)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>InsSclInScen</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>LessUnstable</VALUE>
	<VALUE>Average</VALUE>
	<VALUE>MoreUnstable</VALUE>
	<PROPERTY>position = (538, 469)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>ScnRelPlFcst</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>A</VALUE>
	<VALUE>B</VALUE>
	<VALUE>C</VALUE>
	<VALUE>D</VALUE>
	<VALUE>E</VALUE>
	<VALUE>F</VALUE>
	<VALUE>G</VALUE>
	<VALUE>H</VALUE>
	<VALUE>I</VALUE>
	<VALUE>J</VALUE>
	<VALUE>K</VALUE>
	<PROPERTY>position = (637, 454)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>PlainsFcst</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>NIL</VALUE>
	<VALUE>SIG</VALUE>
	<VALUE>SVR</VALUE>
	<PROPERTY>position = (586, 541)</PROPERTY>
</VARIABLE>


<!-- Probability distributions -->
<PROBABILITY>
	<FOR>WindFieldMt</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.8 0.35 0.75 0.7 0.65 0.15 0.7 0.3 0.5 0.01 0.7 0.2 0.65 0.25 0.3 0.35 0.85 0.3 0.7 0.5 0.99 0.3 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>MorningCIN</FOR>
	<TABLE>0.15 0.57 0.2 0.08 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>VISCloudCov</FOR>
	<TABLE>0.1 0.5 0.4 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>IRCloudCover</FOR>
	<TABLE>0.15 0.45 0.4 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>AMInstabMt</FOR>
	<TABLE>0.333333 0.333333 0.333334 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>R5Fcst</FOR>
	<GIVEN>MountainFcst</GIVEN>
	<GIVEN>N34StarFcst</GIVEN>
	<TABLE>1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 1.0 1.0 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>MountainFcst</FOR>
	<GIVEN>InsInMt</GIVEN>
	<TABLE>1.0 0.48 0.2 0.0 0.5 0.5 0.0 0.02 0.3 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>MeanRH</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.33 0.4 0.05 0.1 0.05 1.0 0.0 0.4 0.2 0.05 0.2 0.5 0.4 0.45 0.5 0.65 0.0 0.07 0.55 0.45 0.55 0.4 0.17 0.2 0.5 0.4 0.3 0.0 0.93 0.05 0.35 0.4 0.4 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>MidLLapse</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.25 0.25 0.4 0.43 0.02 0.0 0.84 0.25 0.41 0.23 0.16 0.55 0.5 0.38 0.37 0.38 0.1 0.16 0.31 0.29 0.42 0.28 0.2 0.25 0.22 0.2 0.6 0.9 0.0 0.44 0.3 0.35 0.56 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>RHRatio</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.05 0.1 0.4 0.2 0.8 0.0 0.6 0.0 0.1 0.4 0.15 0.5 0.5 0.15 0.45 0.05 0.0 0.0 0.7 0.7 0.4 0.45 0.45 0.4 0.45 0.35 0.15 1.0 0.4 0.3 0.2 0.2 0.4 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>LoLevMoistAd</FOR>
	<TABLE>0.12 0.28 0.3 0.3 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>LowLLapse</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.04 0.07 0.35 0.4 0.45 0.01 0.78 0.0 0.22 0.13 0.09 0.25 0.31 0.47 0.4 0.35 0.35 0.19 0.02 0.4 0.4 0.4 0.35 0.31 0.14 0.13 0.15 0.45 0.03 0.33 0.3 0.35 0.33 0.36 0.31 0.04 0.07 0.05 0.19 0.0 0.65 0.08 0.12 0.18 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>MvmtFeatures</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.25 0.05 0.1 0.18 0.02 0.05 0.1 0.0 0.2 0.04 0.5 0.55 0.1 0.3 0.38 0.02 0.07 0.25 0.6 0.1 0.0 0.35 0.2 0.1 0.3 0.34 0.26 0.05 0.15 0.1 0.2 0.04 0.09 0.0 0.75 0.3 0.1 0.7 0.83 0.5 0.3 0.5 0.92 0.06 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>TempDis</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.13 0.15 0.12 0.1 0.04 0.05 0.03 0.05 0.8 0.1 0.2 0.15 0.15 0.1 0.15 0.04 0.12 0.03 0.4 0.19 0.05 0.3 0.1 0.25 0.35 0.4 0.82 0.75 0.84 0.5 0.0 0.4 0.3 0.62 0.45 0.43 0.35 0.1 0.08 0.1 0.05 0.01 0.45 0.2 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>WindAloft</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.0 0.2 0.05 0.03 0.07 0.5 0.25 0.2 0.2 0.96 0.03 0.95 0.3 0.09 0.32 0.66 0.0 0.3 0.14 0.41 0.0 0.08 0.01 0.2 0.59 0.42 0.02 0.0 0.25 0.43 0.1 0.0 0.33 0.04 0.3 0.27 0.23 0.25 0.5 0.2 0.23 0.29 0.04 0.56 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>AMCINInScen</FOR>
	<GIVEN>ScenRelAMCIN</GIVEN>
	<GIVEN>MorningCIN</GIVEN>
	<TABLE>1.0 0.6 0.25 0.0 0.75 0.3 0.01 0.0 0.0 0.37 0.45 0.1 0.25 0.6 0.4 0.03 0.0 0.03 0.3 0.9 0.0 0.1 0.59 0.97 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>CapChange</FOR>
	<GIVEN>CompPlFcst</GIVEN>
	<TABLE>0.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>SynForcng</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.35 0.06 0.1 0.35 0.15 0.15 0.15 0.25 0.25 0.01 0.2 0.25 0.1 0.27 0.2 0.15 0.1 0.1 0.25 0.2 0.05 0.2 0.0 0.06 0.4 0.1 0.1 0.05 0.1 0.25 0.15 0.01 0.35 0.35 0.3 0.08 0.25 0.15 0.15 0.25 0.15 0.2 0.05 0.15 0.05 0.48 0.15 0.1 0.45 0.55 0.4 0.1 0.2 0.88 0.1 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>SatContMoist</FOR>
	<TABLE>0.15 0.2 0.4 0.25 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>RaoContMoist</FOR>
	<TABLE>0.15 0.2 0.4 0.25 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>CombMoisture</FOR>
	<GIVEN>SatContMoist</GIVEN>
	<GIVEN>RaoContMoist</GIVEN>
	<TABLE>0.9 0.6 0.3 0.25 0.55 0.15 0.05 0.1 0.25 0.1 0.0 0.0 0.25 0.25 0.25 0.25 0.1 0.35 0.5 0.35 0.4 0.6 0.4 0.3 0.3 0.35 0.15 0.1 0.25 0.25 0.25 0.25 0.0 0.05 0.2 0.25 0.05 0.2 0.45 0.3 0.35 0.5 0.7 0.4 0.25 0.25 0.25 0.25 0.0 0.0 0.0 0.15 0.0 0.05 0.1 0.3 0.1 0.05 0.15 0.5 0.25 0.25 0.25 0.25 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>LatestCIN</FOR>
	<TABLE>0.4 0.4 0.15 0.05 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>LLIW</FOR>
	<TABLE>0.12 0.32 0.38 0.18 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Date</FOR>
	<TABLE>0.254098 0.131148 0.106557 0.213115 0.07377 0.221312 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>WindFieldPln</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.05 0.08 0.1 0.1 0.43 0.6 0.25 0.04 0.2 0.6 0.1 0.6 0.6 0.0 0.15 0.1 0.07 0.01 0.02 0.3 0.08 0.05 0.02 0.02 0.75 0.2 0.15 0.01 0.3 0.04 0.05 0.07 0.1 0.1 0.1 0.0 0.05 0.06 0.12 0.01 0.8 0.37 0.03 0.05 0.23 0.2 0.0 0.3 0.06 0.2 0.03 0.1 0.07 0.2 0.2 0.0 0.0 0.15 0.2 0.2 0.0 0.4 0.0 0.01 0.02 0.5 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Dewpoints</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.04 0.05 0.4 0.13 0.15 0.0 0.5 0.0 0.0 0.1 0.1 0.05 0.07 0.25 0.22 0.2 0.0 0.27 0.02 0.02 0.45 0.1 0.15 0.15 0.0 0.18 0.2 0.0 0.15 0.1 0.7 0.1 0.1 0.05 0.1 0.15 0.07 0.18 0.0 0.02 0.05 0.0 0.05 0.2 0.19 0.3 0.05 0.34 0.11 0.0 0.02 0.5 0.2 0.26 0.05 0.3 0.27 0.02 0.03 0.11 0.98 0.0 0.2 0.04 0.02 0.1 0.22 0.06 0.13 0.03 0.05 0.02 0.04 0.13 0.04 0.02 0.35 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>SfcWndShfDis</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>0.65 0.65 0.0 0.12 0.06 0.1 0.02 0.01 0.02 0.06 0.05 0.05 0.05 0.65 0.02 0.14 0.1 0.05 0.1 0.1 0.08 0.13 0.1 0.1 0.2 0.02 0.04 0.1 0.05 0.15 0.5 0.04 0.05 0.08 0.1 0.02 0.02 0.04 0.02 0.0 0.4 0.3 0.02 0.39 0.04 0.02 0.06 0.45 0.25 0.0 0.35 0.0 0.01 0.6 0.13 0.07 0.07 0.05 0.27 0.4 0.56 0.33 0.23 0.02 0.14 0.15 0.01 0.01 0.02 0.1 0.07 0.12 0.2 0.11 0.05 0.06 0.1 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>InsChange</FOR>
	<GIVEN>LoLevMoistAd</GIVEN>
	<GIVEN>CompPlFcst</GIVEN>
	<TABLE>0.0 0.0 0.05 0.05 0.1 0.25 0.15 0.2 0.35 0.5 0.8 0.9 0.05 0.12 0.15 0.15 0.4 0.5 0.5 0.6 0.5 0.4 0.16 0.09 0.95 0.88 0.8 0.8 0.5 0.25 0.35 0.2 0.15 0.1 0.04 0.01 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>MorningBound</FOR>
	<TABLE>0.5 0.35 0.15 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>OutflowFrMt</FOR>
	<GIVEN>InsInMt</GIVEN>
	<GIVEN>WndHodograph</GIVEN>
	<TABLE>1.0 1.0 1.0 1.0 0.5 0.15 0.35 0.8 0.05 0.01 0.1 0.6 0.0 0.0 0.0 0.0 0.4 0.4 0.6 0.19 0.45 0.15 0.25 0.3 0.0 0.0 0.0 0.0 0.1 0.45 0.05 0.01 0.5 0.84 0.65 0.1 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>WndHodograph</FOR>
	<TABLE>0.3 0.25 0.25 0.2 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>N34StarFcst</FOR>
	<GIVEN>ScenRel3_4</GIVEN>
	<GIVEN>PlainsFcst</GIVEN>
	<TABLE>0.94 0.06 0.01 0.98 0.04 0.0 0.92 0.01 0.0 0.92 0.03 0.01 0.99 0.09 0.03 0.05 0.89 0.05 0.02 0.94 0.03 0.06 0.89 0.01 0.06 0.92 0.04 0.01 0.9 0.12 0.01 0.05 0.94 0.0 0.02 0.97 0.02 0.1 0.99 0.02 0.05 0.95 0.0 0.01 0.85 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>AreaMoDryAir</FOR>
	<GIVEN>AreaMeso_ALS</GIVEN>
	<GIVEN>CombMoisture</GIVEN>
	<TABLE>0.99 0.7 0.2 0.0 0.8 0.35 0.01 0.0 0.7 0.2 0.01 0.0 0.2 0.05 0.0 0.0 0.01 0.29 0.55 0.25 0.2 0.55 0.39 0.02 0.29 0.6 0.09 0.0 0.74 0.4 0.05 0.0 0.0 0.01 0.24 0.55 0.0 0.1 0.55 0.43 0.01 0.2 0.8 0.3 0.06 0.45 0.5 0.01 0.0 0.0 0.01 0.2 0.0 0.0 0.05 0.55 0.0 0.0 0.1 0.7 0.0 0.1 0.45 0.99 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>CombClouds</FOR>
	<GIVEN>VISCloudCov</GIVEN>
	<GIVEN>IRCloudCover</GIVEN>
	<TABLE>0.95 0.85 0.8 0.45 0.1 0.05 0.1 0.02 0.0 0.04 0.13 0.1 0.52 0.8 0.45 0.4 0.28 0.02 0.01 0.02 0.1 0.03 0.1 0.5 0.5 0.7 0.98 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>ScenRelAMCIN</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>LIfr12ZDENSd</FOR>
	<TABLE>0.1 0.52 0.3 0.08 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>AMDewptCalPl</FOR>
	<TABLE>0.3 0.25 0.45 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>AMInsWliScen</FOR>
	<GIVEN>ScenRelAMIns</GIVEN>
	<GIVEN>LIfr12ZDENSd</GIVEN>
	<GIVEN>AMDewptCalPl</GIVEN>
	<TABLE>0.6 0.85 0.95 0.3 0.5 0.75 0.06 0.2 0.5 0.01 0.05 0.35 0.4 0.7 0.9 0.15 0.25 0.6 0.03 0.2 0.45 0.01 0.05 0.25 0.35 0.55 0.85 0.07 0.2 0.5 0.0 0.05 0.25 0.0 0.0 0.04 0.3 0.5 0.75 0.15 0.2 0.15 0.07 0.13 0.1 0.02 0.04 0.07 0.35 0.4 0.58 0.1 0.15 0.4 0.02 0.05 0.15 0.01 0.03 0.08 0.3 0.4 0.5 0.1 0.25 0.3 0.05 0.1 0.15 0.02 0.04 0.1 0.3 0.13 0.04 0.3 0.3 0.2 0.21 0.4 0.4 0.04 0.2 0.35 0.3 0.2 0.08 0.3 0.5 0.3 0.17 0.3 0.4 0.04 0.18 0.4 0.35 0.4 0.13 0.38 0.6 0.43 0.05 0.35 0.5 0.02 0.05 0.16 0.4 0.3 0.2 0.35 0.6 0.7 0.23 0.47 0.75 0.18 0.26 0.3 0.45 0.5 0.4 0.25 0.45 0.45 0.18 0.25 0.35 0.09 0.17 0.32 0.55 0.5 0.43 0.35 0.5 0.5 0.22 0.35 0.35 0.1 0.16 0.25 0.1 0.02 0.01 0.4 0.2 0.05 0.73 0.4 0.1 0.95 0.75 0.3 0.3 0.1 0.02 0.55 0.25 0.1 0.8 0.5 0.15 0.95 0.77 0.35 0.3 0.05 0.02 0.55 0.2 0.07 0.95 0.6 0.25 0.98 0.95 0.8 0.3 0.2 0.05 0.5 0.2 0.15 0.7 0.4 0.15 0.8 0.7 0.63 0.2 0.1 0.02 0.65 0.4 0.15 0.8 0.7 0.5 0.9 0.8 0.6 0.15 0.1 0.07 0.55 0.25 0.2 0.73 0.55 0.5 0.88 0.8 0.65 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>N0_7muVerMo</FOR>
	<TABLE>0.25 0.25 0.25 0.25 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>SubjVertMo</FOR>
	<TABLE>0.15 0.15 0.5 0.2 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>QGVertMotion</FOR>
	<TABLE>0.15 0.15 0.5 0.2 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>CombVerMo</FOR>
	<GIVEN>N0_7muVerMo</GIVEN>
	<GIVEN>SubjVertMo</GIVEN>
	<GIVEN>QGVertMotion</GIVEN>
	<TABLE>1.0 0.9 0.7 0.2 0.9 0.7 0.15 0.1 0.7 0.15 0.2 0.1 0.2 0.1 0.1 0.1 0.9 0.7 0.15 0.1 0.7 0.0 0.0 0.0 0.15 0.0 0.0 0.0 0.1 0.0 0.0 0.0 0.7 0.15 0.2 0.1 0.15 0.0 0.0 0.0 0.2 0.0 0.0 0.0 0.1 0.0 0.0 0.0 0.2 0.1 0.1 0.1 0.1 0.0 0.0 0.0 0.1 0.0 0.0 0.0 0.1 0.0 0.0 0.0 0.0 0.1 0.2 0.5 0.1 0.3 0.7 0.35 0.2 0.7 0.6 0.2 0.5 0.35 0.2 0.1 0.1 0.3 0.7 0.35 0.3 1.0 0.7 0.2 0.7 0.7 0.3 0.15 0.35 0.2 0.15 0.1 0.2 0.7 0.6 0.2 0.7 0.7 0.3 0.15 0.6 0.3 0.0 0.0 0.2 0.15 0.0 0.0 0.5 0.35 0.2 0.1 0.35 0.2 0.15 0.1 0.2 0.15 0.0 0.0 0.1 0.1 0.0 0.0 0.0 0.0 0.1 0.2 0.0 0.0 0.15 0.45 0.1 0.15 0.2 0.6 0.2 0.45 0.6 0.2 0.0 0.0 0.15 0.45 0.0 0.0 0.3 0.7 0.15 0.3 0.7 0.5 0.45 0.7 0.5 0.2 0.1 0.15 0.2 0.6 0.15 0.3 0.7 0.5 0.2 0.7 1.0 0.7 0.6 0.5 0.7 0.3 0.2 0.45 0.6 0.2 0.45 0.7 0.5 0.2 0.6 0.5 0.7 0.3 0.2 0.2 0.3 0.0 0.0 0.0 0.0 0.1 0.0 0.0 0.0 0.1 0.0 0.0 0.0 0.1 0.1 0.1 0.1 0.6 0.0 0.0 0.0 0.1 0.0 0.0 0.0 0.1 0.0 0.0 0.0 0.35 0.1 0.1 0.35 0.7 0.0 0.0 0.0 0.1 0.0 0.0 0.0 0.35 0.0 0.0 0.0 0.3 0.1 0.35 0.3 0.7 0.1 0.1 0.1 0.6 0.1 0.1 0.35 0.7 0.1 0.35 0.3 0.7 0.6 0.7 0.7 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>AreaMeso_ALS</FOR>
	<GIVEN>CombVerMo</GIVEN>
	<TABLE>1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>CldShadeOth</FOR>
	<GIVEN>AreaMoDryAir</GIVEN>
	<GIVEN>AreaMeso_ALS</GIVEN>
	<GIVEN>CombClouds</GIVEN>
	<TABLE>1.0 0.85 0.25 0.95 0.4 0.05 0.93 0.2 0.01 0.74 0.0 0.0 0.92 0.7 0.15 0.9 0.25 0.01 0.8 0.01 0.0 0.65 0.0 0.0 0.88 0.4 0.1 0.85 0.15 0.0 0.8 0.03 0.0 0.5 0.01 0.0 0.85 0.55 0.1 0.6 0.01 0.0 0.78 0.01 0.0 0.42 0.05 0.0 0.0 0.15 0.35 0.05 0.55 0.45 0.07 0.78 0.29 0.25 0.5 0.1 0.08 0.29 0.4 0.09 0.6 0.3 0.2 0.89 0.1 0.34 0.4 0.02 0.12 0.5 0.4 0.15 0.75 0.2 0.18 0.85 0.05 0.48 0.74 0.01 0.14 0.43 0.25 0.39 0.9 0.15 0.2 0.74 0.04 0.55 0.65 0.0 0.0 0.0 0.4 0.0 0.05 0.5 0.0 0.02 0.7 0.01 0.5 0.9 0.0 0.01 0.45 0.01 0.15 0.69 0.0 0.1 0.9 0.01 0.6 0.98 0.0 0.1 0.5 0.0 0.1 0.8 0.02 0.12 0.95 0.02 0.25 0.99 0.01 0.02 0.65 0.01 0.09 0.85 0.02 0.25 0.96 0.03 0.3 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Boundaries</FOR>
	<GIVEN>OutflowFrMt</GIVEN>
	<GIVEN>WndHodograph</GIVEN>
	<GIVEN>MorningBound</GIVEN>
	<TABLE>0.5 0.3 0.1 0.75 0.45 0.25 0.8 0.35 0.25 0.7 0.25 0.05 0.3 0.1 0.05 0.15 0.1 0.05 0.15 0.05 0.05 0.4 0.2 0.05 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.02 0.01 0.01 0.48 0.5 0.25 0.22 0.45 0.4 0.18 0.5 0.35 0.28 0.6 0.35 0.63 0.5 0.2 0.7 0.75 0.5 0.7 0.8 0.45 0.55 0.65 0.3 0.55 0.4 0.15 0.5 0.4 0.2 0.7 0.5 0.2 0.73 0.5 0.2 0.02 0.2 0.65 0.03 0.1 0.35 0.02 0.15 0.4 0.02 0.15 0.6 0.07 0.4 0.75 0.15 0.15 0.45 0.15 0.15 0.5 0.05 0.15 0.65 0.45 0.6 0.85 0.5 0.6 0.8 0.3 0.5 0.8 0.25 0.49 0.79 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>CldShadeConv</FOR>
	<GIVEN>InsInMt</GIVEN>
	<GIVEN>WndHodograph</GIVEN>
	<TABLE>1.0 1.0 1.0 1.0 0.3 0.2 0.5 0.8 0.0 0.0 0.1 0.5 0.0 0.0 0.0 0.0 0.6 0.7 0.46 0.19 0.3 0.2 0.5 0.38 0.0 0.0 0.0 0.0 0.1 0.1 0.04 0.01 0.7 0.8 0.4 0.12 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>InsInMt</FOR>
	<GIVEN>CldShadeOth</GIVEN>
	<GIVEN>AMInstabMt</GIVEN>
	<TABLE>0.9 0.01 0.0 0.6 0.0 0.0 0.5 0.0 0.0 0.1 0.4 0.05 0.39 0.4 0.0 0.35 0.15 0.0 0.0 0.59 0.95 0.01 0.6 1.0 0.15 0.85 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>ScenRel3_4</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>1.0 0.0 1.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>ScenRelAMIns</FOR>
	<GIVEN>Scenario</GIVEN>
	<TABLE>1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>CompPlFcst</FOR>
	<GIVEN>Boundaries</GIVEN>
	<GIVEN>CldShadeConv</GIVEN>
	<GIVEN>AreaMeso_ALS</GIVEN>
	<GIVEN>CldShadeOth</GIVEN>
	<TABLE>0.4 0.1 0.05 0.6 0.4 0.2 0.6 0.45 0.25 0.7 0.65 0.6 0.4 0.25 0.15 0.65 0.45 0.25 0.65 0.5 0.3 0.75 0.7 0.65 0.45 0.4 0.35 0.7 0.55 0.4 0.7 0.6 0.55 0.85 0.8 0.75 0.35 0.05 0.03 0.5 0.3 0.15 0.55 0.4 0.2 0.6 0.6 0.55 0.35 0.1 0.05 0.55 0.35 0.2 0.6 0.45 0.25 0.65 0.65 0.6 0.4 0.25 0.2 0.65 0.45 0.3 0.65 0.55 0.5 0.78 0.75 0.7 0.3 0.01 0.01 0.35 0.15 0.1 0.45 0.3 0.15 0.5 0.48 0.45 0.3 0.05 0.04 0.4 0.2 0.12 0.5 0.35 0.2 0.55 0.55 0.5 0.3 0.15 0.13 0.5 0.35 0.2 0.55 0.45 0.4 0.7 0.65 0.6 0.35 0.35 0.3 0.25 0.3 0.5 0.35 0.4 0.45 0.27 0.3 0.35 0.35 0.3 0.35 0.25 0.3 0.5 0.3 0.4 0.45 0.23 0.26 0.32 0.3 0.3 0.3 0.22 0.3 0.45 0.27 0.3 0.33 0.14 0.17 0.23 0.35 0.35 0.25 0.25 0.35 0.45 0.3 0.4 0.4 0.35 0.3 0.33 0.35 0.35 0.3 0.25 0.35 0.5 0.3 0.4 0.5 0.3 0.3 0.35 0.35 0.4 0.4 0.25 0.35 0.5 0.3 0.3 0.3 0.18 0.2 0.25 0.3 0.25 0.2 0.25 0.4 0.35 0.3 0.4 0.4 0.35 0.32 0.35 0.3 0.6 0.27 0.25 0.4 0.43 0.3 0.4 0.45 0.35 0.3 0.4 0.35 0.35 0.35 0.25 0.35 0.45 0.35 0.35 0.35 0.24 0.28 0.3 0.25 0.55 0.65 0.15 0.3 0.3 0.05 0.15 0.3 0.03 0.05 0.05 0.25 0.45 0.5 0.1 0.25 0.25 0.05 0.1 0.25 0.02 0.04 0.03 0.25 0.3 0.35 0.08 0.15 0.15 0.03 0.1 0.12 0.01 0.03 0.02 0.3 0.6 0.72 0.25 0.35 0.4 0.15 0.2 0.4 0.05 0.1 0.12 0.3 0.55 0.65 0.2 0.3 0.3 0.1 0.15 0.25 0.05 0.05 0.05 0.25 0.35 0.4 0.1 0.2 0.2 0.05 0.15 0.2 0.04 0.05 0.05 0.4 0.74 0.79 0.4 0.45 0.55 0.25 0.3 0.45 0.15 0.2 0.2 0.4 0.35 0.69 0.35 0.4 0.45 0.2 0.25 0.35 0.1 0.15 0.1 0.35 0.5 0.52 0.25 0.3 0.35 0.1 0.2 0.25 0.06 0.07 0.1 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>CurPropConv</FOR>
	<GIVEN>LatestCIN</GIVEN>
	<GIVEN>LLIW</GIVEN>
	<TABLE>0.7 0.1 0.01 0.0 0.9 0.65 0.25 0.01 0.95 0.75 0.4 0.2 1.0 0.95 0.75 0.5 0.28 0.5 0.14 0.02 0.09 0.25 0.35 0.15 0.05 0.23 0.4 0.3 0.0 0.05 0.2 0.35 0.02 0.3 0.35 0.18 0.01 0.09 0.3 0.33 0.0 0.02 0.18 0.35 0.0 0.0 0.05 0.1 0.0 0.1 0.5 0.8 0.0 0.01 0.1 0.51 0.0 0.0 0.02 0.15 0.0 0.0 0.0 0.05 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Scenario</FOR>
	<GIVEN>Date</GIVEN>
	<TABLE>0.1 0.05 0.04 0.04 0.04 0.05 0.16 0.16 0.13 0.13 0.11 0.11 0.1 0.09 0.1 0.09 0.1 0.1 0.08 0.09 0.08 0.07 0.07 0.08 0.08 0.12 0.15 0.2 0.17 0.11 0.01 0.02 0.03 0.08 0.05 0.02 0.08 0.13 0.14 0.06 0.1 0.11 0.1 0.06 0.04 0.05 0.05 0.06 0.09 0.07 0.06 0.07 0.07 0.08 0.03 0.11 0.15 0.13 0.14 0.11 0.17 0.1 0.08 0.08 0.1 0.17 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>CapInScen</FOR>
	<GIVEN>AMCINInScen</GIVEN>
	<GIVEN>CapChange</GIVEN>
	<TABLE>1.0 0.98 0.35 0.75 0.03 0.0 0.3 0.0 0.0 0.0 0.02 0.35 0.25 0.94 0.25 0.35 0.02 0.0 0.0 0.0 0.3 0.0 0.03 0.75 0.35 0.98 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>InsSclInScen</FOR>
	<GIVEN>AMInsWliScen</GIVEN>
	<GIVEN>InsChange</GIVEN>
	<TABLE>1.0 0.9 0.4 0.6 0.15 0.0 0.25 0.0 0.0 0.0 0.1 0.35 0.4 0.7 0.4 0.35 0.1 0.0 0.0 0.0 0.25 0.0 0.15 0.6 0.4 0.9 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>ScnRelPlFcst</FOR>
	<GIVEN>Scenario</GIVEN>