<?XML VERSION="1.0"?>


<!--
	Bayesian network in BIF (BayesNet Interchange Format)
	Produced by JavaBayes (http://www.cs.cmu.edu/~javabayes/
	Output created Thu Aug 06 08:02:17 GMT+01:00 1998
-->



<!-- DTD for the BIF format -->
<!DOCTYPE BIF [
	<!ELEMENT BIF ( NETWORK )*>
	<!ELEMENT PROPERTY (#PCDATA)>
	<!ELEMENT TYPE (#PCDATA)>
	<!ELEMENT VALUE (#PCDATA)>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT NETWORK
	    ( NAME, ( PROPERTY | VARIABLE | PROBABILITY )* )>
	<!ELEMENT VARIABLE ( NAME, TYPE, ( VALUE |  PROPERTY )* ) >
	<!ELEMENT PROBABILITY
	    ( FOR | GIVEN | TABLE | ENTRY | DEFAULT | PROPERTY )* >
	<!ELEMENT FOR (#PCDATA)>
	<!ELEMENT GIVEN (#PCDATA)>
	<!ELEMENT TABLE (#PCDATA)>
	<!ELEMENT DEFAULT (TABLE)>
	<!ELEMENT ENTRY ( VALUE* , TABLE )>
]>


<BIF>
<NETWORK>
<NAME>Asia</NAME>

<!-- Variables -->
<VARIABLE>
	<NAME>VisitAsia</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Visit</VALUE>
	<VALUE>NoVisit</VALUE>
	<PROPERTY>position = (138, 187)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Tuberculosis</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Present</VALUE>
	<VALUE>Absent</VALUE>
	<PROPERTY>position = (225, 235)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Smoking</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Smoker</VALUE>
	<VALUE>NonSmoker</VALUE>
	<PROPERTY>position = (533, 180)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Cancer</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Present</VALUE>
	<VALUE>Absent</VALUE>
	<PROPERTY>position = (437, 245)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>TbOrCa</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>True</VALUE>
	<VALUE>False</VALUE>
	<PROPERTY>position = (351, 304)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>XRay</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Abnormal</VALUE>
	<VALUE>Normal</VALUE>
	<PROPERTY>position = (256, 373)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Bronchitis</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Present</VALUE>
	<VALUE>Absent</VALUE>
	<PROPERTY>position = (625, 242)</PROPERTY>
</VARIABLE>

<VARIABLE>
	<NAME>Dyspnea</NAME>
	<TYPE>discrete</TYPE>
	<VALUE>Present</VALUE>
	<VALUE>Absent</VALUE>
	<PROPERTY>position = (492, 374)</PROPERTY>
</VARIABLE>


<!-- Probability distributions -->
<PROBABILITY>
	<FOR>VisitAsia</FOR>
	<TABLE>0.01 0.99 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Tuberculosis</FOR>
	<GIVEN>VisitAsia</GIVEN>
	<TABLE>0.05 0.01 0.95 0.99 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Smoking</FOR>
	<TABLE>0.5 0.5 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Cancer</FOR>
	<GIVEN>Smoking</GIVEN>
	<TABLE>0.1 0.01 0.9 0.99 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>TbOrCa</FOR>
	<GIVEN>Tuberculosis</GIVEN>
	<GIVEN>Cancer</GIVEN>
	<TABLE>1.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>XRay</FOR>
	<GIVEN>TbOrCa</GIVEN>
	<TABLE>0.98 0.05 0.02 0.95 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Bronchitis</FOR>
	<GIVEN>Smoking</GIVEN>
	<TABLE>0.6 0.3 0.4 0.7 </TABLE>
</PROBABILITY>

<PROBABILITY>
	<FOR>Dyspnea</FOR>
	<GIVEN>TbOrCa</GIVEN>
	<GIVEN>Bronchitis</GIVEN>
	<TABLE>0.9 0.7 0.8 0.1 0.1 0.3 0.2 0.9 </TABLE>
</PROBABILITY>


</NETWORK>
</BIF>
